# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: e39314dbbe12b473da39ff79e9db25537cfee32ad980d010f5c1abcd8bb969eb6cca4b9125e3d50000e4a7f9110b2f89093feb84d3c3ff5201e9c9ed46a90a9e

test:
  secret_key_base: 4b988f47988b1ca2d3758bf8d76d993213a7d2436edf1bbc247f1952e1ff6b980c0f8b37a7387841a3a003a99ee62c207261cd9d2708808adff22abe2a91e50c

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
